// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsRFjv7jOoj46ZWefvl8k1zMmFWgUP1iQ',
    appId: '1:191108466730:web:1a2d28d0b3f7262584db53',
    messagingSenderId: '191108466730',
    projectId: 'multimeister-7fe9d',
    authDomain: 'multimeister-7fe9d.firebaseapp.com',
    storageBucket: 'multimeister-7fe9d.appspot.com',
    measurementId: 'G-X1YHGYGDN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-hyRWpMsAVvico2sijdfcB91cxcKnd2k',
    appId: '1:191108466730:android:cf79171080ded33684db53',
    messagingSenderId: '191108466730',
    projectId: 'multimeister-7fe9d',
    storageBucket: 'multimeister-7fe9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC79BqWShwySCCrzkeDLfGWi2GP-AMcuII',
    appId: '1:191108466730:ios:49f3a783f20d746184db53',
    messagingSenderId: '191108466730',
    projectId: 'multimeister-7fe9d',
    storageBucket: 'multimeister-7fe9d.appspot.com',
    iosClientId: '191108466730-1tvf74c6dc1uam694t8hegl0mhvajhag.apps.googleusercontent.com',
    iosBundleId: 'com.example.multimeister',
  );
}
